%>@ingroup codegen guigroup
%>@file
%>@brief Creates a few objects in the base workspace
%>
%> @params 
function create_default_objects()


code = sprintf([...
'clssr_default = def_clssr();\n', ...
'peakdetector_default = def_peakdetector();\n', ...
'sgs_default = def_sgs();\n', ...
'subsetsprocessor_default = def_subsetsprocessor();\n', ...
'biocomparer_default = def_biocomparer();\n', ...
'postpr_test_default = def_postpr_test();\n', ...
'postpr_est_default = def_postpr_est();\n', ...
'fsg_clssr_default = fsg_clssr();\n', ...
'fsg_clssr_default.clssr = clssr_default;\n', ...
'fsg_clssr_default.sgs = sgs_default;\n', ...
]);

ircode_eval(code, 'Creating some default objects...');
