%>@ingroup idata
%>@file
%>@brief Welcome message

function s = get_welcome()

s = sprintf([
' * \n' ...
' * Welcome to IRootLab\n', ...
' * \n' ...
' *   - User Interfaces: <a href="matlab: objtool">objtool</a>, <a href="matlab: mergetool">mergetool</a>, <a href="matlab: irootlabgui">irootlabgui</a>, <a href="matlab: sheload">sheload</a>\n *\n' ...
' *   - Open help in browser: <a href="matlab: help2">help2</a>\n *\n' ...
' *   - Demos: <a href="matlab: browse_demos">browse_demos</a>\n *\n' ...
' *   - Official website: <a href="http://irootlab.googlecode.com">http://irootlab.googlecode.com</a>\n *\n' ...
]);
