%>@ingroup idata htmlgen
%>@file
%>@brief Returns HTML stylesheet
%>
%> Check source code for available styles

function s = stylesheet()
s = [
'<style>', 10, ...
'h1 {font-family: Times New Roman, serif; font-size:18pt; font-weight: bold; text-align: center;}', 10, ...
'h2 {font-family: Times New Roman, serif; font-size:15pt; font-weight: bold; text-align: center;}', 10, ...
'h3 {font-family: Times New Roman, serif; font-size:14pt; font-weight: bold; text-align: center;}', 10, ...
'h4 {font-family: Times New Roman, serif; font-size:13pt; font-weight: bold; text-align: center;}', 10, ...
'h5 {font-family: Times New Roman, serif; font-size:12pt; font-weight: bold; text-align: center;}', 10, ...
'td {font-family: Times New Roman; padding: 3px}', 10, ...
'td {border: 0; border-collapse: collapse; border-spacing: 0px; }', 10, ...
'td {padding: 4px;}', 10, ...
'.nu, .tdnu {text-align: right}', 10, ...
'.her {text-align: right; font-weight: bold;}', 10, ...
'.hel, .tdle {text-align: left; font-weight: bold;}', 10, ...
'.hec, .tdhe {text-align: center; font-weight: bold;}', 10, ...
'.ce {text-align: center;}', 10, ...
'.ri {text-aligh: right;}', 10, ...
'.sma {font-size: 9pt;}', 10, ...
'.nobo {border: 0}', 10, ...
'.bo {border: 2px solid black; border-collapse: collapse; border-spacing: 0px;}', 10, ... % Border
'.bob {border-collapse: collapse; border-spacing: 0px; border-bottom-style: solid; border-bottom-width: 2}', 10, ... % Border bottom
'.bob1 {border-collapse: collapse; border-spacing: 0px; border-bottom-style: solid; border-bottom-width: 1}', 10, ...
'.bor {border-collapse: collapse; border-spacing: 0px; border-right-style: solid; border-right-width: 2}', 10, ... % Border right
'.bobbor {border-collapse: collapse; border-spacing: 0px; border-bottom-style: solid; border-bottom-width: 2; border-right-style: solid; border-right-width: 2}', 10, ...
'.backbet {background-color: #d8ffd8}', 10, ...
'.foresig {font-weight: bold; color: #004000}', 10, ...
'.helchoa {text-align: left;font-weight: bold; background-color: #800000; color: #fefefe;}', 10, ...
'.nuchoa {text-align: right; font-weight: bold; background-color: #800000; color: #fefefe;}', 10, ...
'</style>', 10, ...
'', 10];
