% This function was created to centralize the information about single-spectrum types
function P = get_spfile_descriptions()
P = {'Pirouette .DAT" text format', ...
     'OPUS binary format', ...
     'Wire TXT format', ...
     'Wire (2016) TXT format', ...
     'Diane''s "Another FTIR" (2017) TXT format', ...
     'BWSpec CSV format' ...
     };

 

