%> This SODATAITEM is generated by a FeaHistGenerator
classdef soitem_fhgs < soitem_fhg
    properties
        %> Array of @ref log_fselrepeater
        logs;
        %> Cell of @ref soitem
        items;
    end;
end
