%> This SODATAITEM is generated by a FEARCHSEL_FS
%>
%> This is used by other FED_FS as well. I didn't change the name of the property not to mess with the results already generated
classdef soitem_fs < soitem_sostagechoice
    properties
        %> log_as_fsel object
        log_as_fsel;
    end;
end
