var group__string =
[
    [ "get_matlab_output.m", "get__matlab__output_8m.html", null ],
    [ "get_suffix.m", "get__suffix_8m.html", null ],
    [ "cell2csv.m", "cell2csv_8m.html", null ],
    [ "cell2str.m", "cell2str_8m.html", null ],
    [ "classlabels2cell.m", "classlabels2cell_8m.html", null ],
    [ "convert_to_str.m", "convert__to__str_8m.html", null ],
    [ "int2ord.m", "int2ord_8m.html", null ],
    [ "params2str.m", "params2str_8m.html", null ],
    [ "params2str2.m", "params2str2_8m.html", null ],
    [ "parse_classmaps.m", "parse__classmaps_8m.html", null ],
    [ "get_no_cols_deli.m", "get__no__cols__deli_8m.html", null ],
    [ "good_filename.m", "good__filename_8m.html", null ],
    [ "good_varname.m", "good__varname_8m.html", null ],
    [ "resolve_dir.m", "resolve__dir_8m.html", null ],
    [ "cell2html.m", "cell2html_8m.html", null ],
    [ "cellcolor.m", "cellcolor_8m.html", null ],
    [ "confusion_cell.m", "confusion__cell_8m.html", null ],
    [ "confusion_str.m", "confusion__str_8m.html", null ],
    [ "fel.m", "fel_8m.html", null ],
    [ "format_number.m", "format__number_8m.html", null ],
    [ "html_comparison.m", "html__comparison_8m.html", null ],
    [ "html_comparison_std.m", "html__comparison__std_8m.html", null ],
    [ "html_confusion.m", "html__confusion_8m.html", null ],
    [ "html_table_std.m", "html__table__std_8m.html", null ],
    [ "html_table_std_colors.m", "html__table__std__colors_8m.html", null ],
    [ "replace_underscores.m", "replace__underscores_8m.html", null ],
    [ "strip_code.m", "strip__code_8m.html", null ],
    [ "strip_quotes.m", "strip__quotes_8m.html", null ],
    [ "uniquenesses.m", "uniquenesses_8m.html", null ],
    [ "menu.m", "menu_8m.html", null ]
];