var group__datasettools =
[
    [ "data_draw.m", "data__draw_8m.html", null ],
    [ "data_draw_3dhist.m", "data__draw__3dhist_8m.html", null ],
    [ "data_draw_covariance.m", "data__draw__covariance_8m.html", null ],
    [ "data_draw_hachures.m", "data__draw__hachures_8m.html", null ],
    [ "data_draw_means.m", "data__draw__means_8m.html", null ],
    [ "data_draw_pca_pareto.m", "data__draw__pca__pareto_8m.html", null ],
    [ "data_draw_scatter_1d.m", "data__draw__scatter__1d_8m.html", null ],
    [ "data_draw_scatter_2d.m", "data__draw__scatter__2d_8m.html", null ],
    [ "data_draw_scatter_3d.m", "data__draw__scatter__3d_8m.html", null ],
    [ "data_draw_scatter_3d2.m", "data__draw__scatter__3d2_8m.html", null ],
    [ "draw3d2_adjust.m", "draw3d2__adjust_8m.html", null ],
    [ "draw3d2_core.m", "draw3d2__core_8m.html", null ],
    [ "draw3d2_get_minmax.m", "draw3d2__get__minmax_8m.html", null ],
    [ "data_assign_splitidxs.m", "data__assign__splitidxs_8m.html", null ],
    [ "data_get_cv.m", "data__get__cv_8m.html", null ],
    [ "data_get_legend.m", "data__get__legend_8m.html", null ],
    [ "data_isolate_class.m", "data__isolate__class_8m.html", null ],
    [ "data_merge_cols.m", "data__merge__cols_8m.html", null ],
    [ "data_merge_rows.m", "data__merge__rows_8m.html", null ],
    [ "data_rename_classlabels.m", "data__rename__classlabels_8m.html", null ],
    [ "data_renumber_classes.m", "data__renumber__classes_8m.html", null ],
    [ "data_select_groups.m", "data__select__groups_8m.html", null ],
    [ "data_select_hierarchy.m", "data__select__hierarchy_8m.html", null ],
    [ "data_select_inliers.m", "data__select__inliers_8m.html", null ],
    [ "data_sort_by_group.m", "data__sort__by__group_8m.html", null ],
    [ "data_sort_classlabels.m", "data__sort__classlabels_8m.html", null ],
    [ "data_split_classes.m", "data__split__classes_8m.html", null ],
    [ "data_split_classmap.m", "data__split__classmap_8m.html", null ],
    [ "data_split_groups.m", "data__split__groups_8m.html", null ],
    [ "data_split_sgs.m", "data__split__sgs_8m.html", null ],
    [ "detect_file_type.m", "detect__file__type_8m.html", null ],
    [ "data_eliminate_var0.m", "data__eliminate__var0_8m.html", null ]
];