var group__conversion =
[
    [ "cell2classlabels.m", "cell2classlabels_8m.html", null ],
    [ "cell2csv.m", "cell2csv_8m.html", null ],
    [ "cell2str.m", "cell2str_8m.html", null ],
    [ "classes2boolean.m", "classes2boolean_8m.html", null ],
    [ "classes2labels.m", "classes2labels_8m.html", null ],
    [ "classes2legends.m", "classes2legends_8m.html", null ],
    [ "classlabels2cell.m", "classlabels2cell_8m.html", null ],
    [ "classlabels2classmap.m", "classlabels2classmap_8m.html", null ],
    [ "classmap2obsmap.m", "classmap2obsmap_8m.html", null ],
    [ "color2hex.m", "color2hex_8m.html", null ],
    [ "colors2map.m", "colors2map_8m.html", null ],
    [ "compare_classes.m", "compare__classes_8m.html", null ],
    [ "convert_to_str.m", "convert__to__str_8m.html", null ],
    [ "get_feaidxs.m", "get__feaidxs_8m.html", null ],
    [ "get_probs.m", "get__probs_8m.html", null ],
    [ "int2ord.m", "int2ord_8m.html", null ],
    [ "params2str.m", "params2str_8m.html", null ],
    [ "params2str2.m", "params2str2_8m.html", null ],
    [ "parse_classmaps.m", "parse__classmaps_8m.html", null ],
    [ "percs2no_unitss.m", "percs2no__unitss_8m.html", null ],
    [ "renumber_classes.m", "renumber__classes_8m.html", null ],
    [ "renumber_group_indexes.m", "renumber__group__indexes_8m.html", null ],
    [ "renumber_vector_idooo.m", "renumber__vector__idooo_8m.html", null ],
    [ "splitidxs2maps.m", "splitidxs2maps_8m.html", null ],
    [ "subsets2matrix.m", "subsets2matrix_8m.html", null ],
    [ "v_ind2x.m", "v__ind2x_8m.html", null ],
    [ "v_x2ind.m", "v__x2ind_8m.html", null ],
    [ "classes2colormap.m", "classes2colormap_8m.html", null ],
    [ "itemlist2cell.m", "itemlist2cell_8m.html", null ],
    [ "cy.m", "cy_8m.html", null ],
    [ "make_one.m", "make__one_8m.html", null ],
    [ "strip_code.m", "strip__code_8m.html", null ],
    [ "strip_quotes.m", "strip__quotes_8m.html", null ],
    [ "uniquenesses.m", "uniquenesses_8m.html", null ]
];