var modules =
[
    [ "Maintenance of global variables", "group__globals.html", "group__globals" ],
    [ "Reinforcement routines", "group__assert.html", "group__assert" ],
    [ "Setup routines", "group__setupgroup.html", "group__setupgroup" ],
    [ "Hard-coded internal data (default setups, chemical information, etc), anything that has constants, really", "group__idata.html", "group__idata" ],
    [ "Main Graphical User Interfaces (GUIs)", "group__mainguis.html", "group__mainguis" ],
    [ "All GUIs", "group__guigroup.html", "group__guigroup" ],
    [ "Graphical API", "group__graphicsapi.html", "group__graphicsapi" ],
    [ "Conversion between variable types and formats", "group__conversion.html", "group__conversion" ],
    [ "Communication with the user", "group__usercomm.html", "group__usercomm" ],
    [ "Data Input/Output routines", "group__ioio.html", "group__ioio" ],
    [ "String manipulation", "group__string.html", "group__string" ],
    [ "HTML generation rountines", "group__htmlgen.html", "group__htmlgen" ],
    [ "Routines to manipulate/convert (data classes) / (data class labels)", "group__classlabelsgroup.html", "group__classlabelsgroup" ],
    [ "Routines to manipulate/convert data groups", "group__groupgroup.html", "group__groupgroup" ],
    [ "Maths rountines", "group__maths.html", "group__maths" ],
    [ "Any \"math\"?", "group__math.html", null ],
    [ "Parallel programming", "group__parallelgroup.html", "group__parallelgroup" ],
    [ "Interface with (the SHEware database) / (databases in general)", "group__sheware.html", "group__sheware" ],
    [ "(Code generation routines) / (interaction with the workspace)", "group__codegen.html", "group__codegen" ],
    [ "Demo files", "group__demo.html", "group__demo" ],
    [ "Interactive scripts", "group__interactive.html", "group__interactive" ],
    [ "Non-official methods from the irdata class", "group__datasettools.html", "group__datasettools" ],
    [ "Routines that tamper with the IRootLab source code", "group__introspection.html", "group__introspection" ],
    [ "Miscellanea", "group__misc.html", "group__misc" ],
    [ "Compatibility with older versions", "group__compat.html", "group__compat" ],
    [ "System Optimization Framework", "group__soframework.html", "group__soframework" ],
    [ "Sample Data", "group__sampledata.html", "group__sampledata" ]
];